travel:
    poiDetailsApis:
        baseurl : ${base_url}
        apikey : ${api_key}
        findPlace : ${find_place}
        poiDetail : ${details}
        nearby : ${near_by_search}
        fields : formatted_address,geometry,icon,id,name,permanently_closed,photos,place_id,plus_code,types,opening_hours,price_level,rating
    ticket1_S:
        baseurl: ${ticket1_base_url}
        apiKey: ${ticket1_api_key}
        tour: ${ticket1_tours}
    ticket2_T:
        baseurl : ${ticket2_base_url}
        account : ${account}
        token : ${token}
        tour : ${tour_url}